### ISSUE TITLE
SMS commands and notifications

### ISSUE THREAD

**Issue by Armagetron** [tananaev/traccar-client-android#106]
I have added SMS functionality to the traccar client. You can now receive position updates through SMS messages. These SMS are send to a configured number in the app. This feature can be toggled on or off. These updates are in addition to the normal logging via the internet connection.

This functionality is useful for users who live in remote locations where SMS is still working but the mobile internet is not.

The client can also be controlled via SMS. I have implemented the following commands (which are send via SMS to the device):
- pos -> returns one answer containing the time of the position date, latitude, longitude, altitude, speed and remaining battery
- enable -> enables the sms logging
- disable -> disables the sms logging

Here are two screenshots. The first shows the additional menu items and the second one a log entry of a SMS. You can check out the changes in [my forked repository](https://github.com/Armagetron/traccar-client-android). I would like to hear your thoughts!

![screen01](https://cloud.githubusercontent.com/assets/8214745/4114279/b4e52eb0-3264-11e4-9c32-d1dc23c5db88.png)
![screen02](https://cloud.githubusercontent.com/assets/8214745/4114280/b4e5ac50-3264-11e4-8a9b-8a72a3a0bfa6.png)

**Comment by aacable** [comment]
any update on the sms feature?
can you please help how to add ADDRESS column in archive view and in map?


Regards, 
SYED JAHANZAIB 

 








 Date: Tue, 16 Dec 2014 23:23:13 -0800

**Comment by Armagetron** [comment]
> any update on the sms feature?

I haven't worked on the client but on other features related to it on my server.

> can you please help how to add ADDRESS column in archive view and in map?

This is a completely different issue and has nothing to do with sms.

**Comment by redge76** [comment]
Hi,
I also second this feature request. Where I live, data connection is quite bad. SMS is a lot more reliable. So It would be great to have such an option as "if position update by 3G not possible for 10 minutes, send location by SMS". I would like to install a cheap 3G USB key on my server with smstools3. When a SMS is received, it is analysed and a http request is sent to traccar to update position.
Regards,
Regis

**Comment by scietech9** [comment]
hello sir Armagetron,., can i ask something about your android., can i get your email address? thankyou

**Comment by Armagetron** [comment]
I would like to invite everyone who is interested in sms support to discuss features in my fork.

**Comment by Armagetron** [comment]
@redge76: I got something like that running on an Raspberry Pi. It uses an Huawei UMTS Stick which receives SMS from traccar, converts them to the traccar protocol (because I want the SMS to be human readable) and sends them to the tracking server. SMS handling is done using the gammu library and a piece of software that process the SMS.

For those of you who are still interested into it, I have currently updated the settings screen. Now I am redoing the UI. This will allow me to integrate other features using more screens/fragments.

**Comment by redge76** [comment]
Sure I'm still interested...

**Comment by redge76** [comment]
Any news about this client with SMS commands? Here is my use case:
My friend ride horses. She goes sometime alone in the woods. So I need a client that:
 - When data connection is available, the position is sent every 2/3 minutes and stored to be sent later if connection is not available. (this is already available with the current version of the client)
- If data connection is not available for more than 10/15 minutes, a SMS is sent with the last GPS position. (or x last positions, but we only have 140 ..). This SMS can ether be sent to a human or to a 3g dongle attached to the traccar server. It could also be to a smartphone with an application able to translate the SMS to a traccar position update.
 - In the event she fall of her horse and is unable to call for help, I need to know the last position. So the application would react to a SMS by sending the last know position. (this seems to be available in the armagetron client)

Why SMS is so important ? because 3G if generally not available where she rides. It's too far in the country. It can be miles before she find a strong enough signal to the position backlog.

Armagetron can you provide a compiled client ?

**Comment by mattbk** [comment]
+1 for SMS delivery of positions to the server. I put on endurance events, some in remote locations, where data availability is spotty or nonexistent.

**Comment by tananaev** [comment]
SMS notifications are already available. Server doesn't decode SMS positions, but it will show save any incoming SMS as events.
