### ISSUE TITLE
Background service silently Killed on Samsung Galaxy S6 android 5.1.1

### ISSUE THREAD

**Issue by horbith** [tananaev/traccar-client-android#175]
Hi @tananaev 
First thank you for this amazing app.
I have installed latest version from git on Samsung Galaxy S6 android 5.1.1, the app working fine but after few hour i found that the service was destroyed. then when i start the app with calling 8722227 and i check status from app menu i found that the service was just created.

Thanks

**Comment by tananaev** [comment]
It is possible to get Android logs from the device?

**Comment by zonlee181** [comment]
Go to Smart manager
click on battery,
click on Detail, 
turn off App optimisation.



i also notice, the app stop working after i run waze.

**Comment by edtheitguy** [comment]
I have the same problem with/on different samsung devices, after a few days, sometimes only hours the tracking stops and there is no notice in status log.

I didnt dig into it but I think its the same problem that I had with my app always getting killed on samsung devices.
I am not exactly sure which error it was or if both cicked in: "inactivity" or "low memory".
Maybe its just a samsung thingy that they kill background apps that arent used after a certain amount of time....

However, I solved it by simply adding a restart after stop, I used:
(not on my dev pc so cant check/say if the names are right)
start-redeliver-intent / start-sticky

That solved my problems, app now runs since nov. without any hickups.

**Comment by tananaev** [comment]
I guess I need to implement some way to re-start service in case it gets killed by the system.

**Comment by edtheitguy** [comment]
I had the same problems:
You can "hide" it and even prevent access or deinstall but I dont know any way how to prevent it being "disabled/stopped" outside the app itself e.g. via manager or other memory/system app.
Todays techie kids find lockout workaround solutions faster then you can dail a number ;) 

So in general its not a bad option idea.
Something like if its active/enabled it auto restarts when killed or disabled/stopped outside of the app thru any other app.

**Comment by SudoHenk** [comment]
Same problem on Galaxy S5. I tried turning off app optimization but service still gets killed after 3 days.

**Comment by SudoHenk** [comment]
@tananaev thanks for fixing it, when will this be on Google Play?

**Comment by tananaev** [comment]
It's already on Google Play. It might take some time for Google to review and approve the release.

**Comment by rickythefox** [comment]
Won't this fix kill your battery by waking the device every 15 sec and preventing deep sleep?

**Comment by SudoHenk** [comment]
I'm running passive GPS tracking every 20 minutes now and did not notice a dramatic change in battery life.

**Comment by tananaev** [comment]
It's inexact repeating alarm. Most likely you already have some other apps (possibly Android system) that will wake your phone up every 15 minutes anyway, so it shouldn't affect battery life much.

**Comment by Cruise360** [comment]
I've noticed that this has been stopping my tracking app recently too!!
Is a start-sticky is the best workaround at present?

**Comment by tananaev** [comment]
@Cruise360, I'm not sure what start-sticky workaround you are talking about. Workaround for the Samsung issue is to use AlarmManager.
