### ISSUE TITLE
Update Position only if a certain distance lies between the last position and the current one

### ISSUE THREAD

**Issue by ngt-github** [tananaev/traccar-client-android#254]
Hi, I am using the traccar client on android and a normal Apache as server. The Position is sent periodically and it's running pretty well.
To reduce the mobile traffic, an option "distance" would be great.
Only make a GET-Request to update the position, when the distance to the previous transferred position is greater than the distance given in the options.
Also this would prevent the car wandering around on the map, if it stands somewhere with bad gps-signal. (To a certain degree at least).
Setting distance to 0 als default won't change the behaviour to the current version.

As a fallback, you maybe want to consider to transfer the position every n seconds, no matter what distance is given.

As the cars that I want to track only travel short distances and are standing 95% of the time, this would greatly reduce the traffic.

Hope you understand what I am talking about - if not feel free to ask.
Thanks!

**Comment by tananaev** [comment]
This has already been requested before and I agree in general. I will try to implement it as soon as I find time.

**Comment by ke5stl** [comment]
you might also consider having the location sent if the direction changes by more than x degrees.  eg: this way, with a value to rate-limit updates due to direction changes.  this way, you could set the 'regular interval' to a fairly high number, and use the direction and distance triggers to send an update when something is happening.  and, you might want to set a speed above which the distance needed per update is increased linearly with speed over a given speed.  and, if the device becomes stationary for x amount of time, and, then starts moving after having been at rest.

**Comment by Anton-V-K** [comment]
Version 5.5 supports reporting distance in meters (with 0 as default). I guess, the issue may be closed...

**Comment by ke5stl** [comment]
Thank you very much.

 

This is really helpful.
